blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/Thespaceblade/F1-Corner-Analysis/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/Thespaceblade/F1-Corner-Analysis/tree/main/docs
    about: Check the documentation for more information




